baseURL = "https://www.chattertots.net"
languageCode = "en-gb"
theme = "sawmill"
title = "Chattertots"
googleAnalytics = "UA-32275738-1"

[Author]
name = "Louise Hibbert"
[[menu.main]]
name = "View on Github"
url = "https://chattertots.net"
weight = 10
[params]
logo = "/logo.svg"
description = "Speech and Language Therapy in Surrey"
images = ["site-feature-image.jpg"]
[permalinks]
  posts = "/:year/:month/:title/"