baseURL = "https://chattertots.netlify.com"
enableRobotsTXT = true
googleAnalytics = "UA-32275738-1"
languageCode = "en-gb"
theme = "sawmill"
title = "Chattertots"
[Author]
name = "Louise Hibbert"
sectionPagesMenu = "main"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 6
[[menu.main]]
identifier = "testimonials"
name = "Testimonials"
url = "/testimonials/"
weight = 4
[[menu.main]]
identifier = "qualifications"
name = "Qualifications"
url = "/qualifications/"
weight = 3
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 2
[[menu.main]]
identifier = "whattoexpect"
name = "What to expect"
url = "/what-to-expect/"
weight = 1
[params]
description = "Speech and Language Therapy in Surrey"
images = ["site-feature-image.jpg"]
logo = "/chattertotslogo.svg"
[permalinks]
posts = "/:year/:month/:title/"
[sitemap]
filename = "sitemap.xml"
